# Generated by Django 6.0.3 on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                (
                    'employee_id',
                    models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
                ),
                (
                    'department',
                    models.CharField(blank=True, default=None, max_length=150, null=True),
                ),
                (
                    'qualification',
                    models.CharField(blank=True, default=None, max_length=150, null=True),
                ),
                ('experience_years', models.IntegerField(blank=True, default=None, null=True)),
                (
                    'email',
                    models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
                ),
                (
                    'dp',
                    models.ImageField(blank=True, default=None, null=True, upload_to='teacher_dp/'),
                ),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('joining_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
