# Generated by Django 6.0.3 on 2026-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_normalize_faculty_and_enrollment_year'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='student.faculty'),
        ),
    ]
