# Generated by Django 6.0.3 on 2026-04-06 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_student_fac_year_idx_and_more'),
        ('teacher', '0003_teacher_user_is_first_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['name'], name='teacher_name_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['department'], name='teacher_dept_idx'),
        ),
    ]
