# Generated by Django 6.0.3 on 2026-04-06 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_user_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='student.faculty'),
        ),
    ]
