# Generated by Django 6.0.3 on 2026-04-06 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_subject_abbreviation_subject_faculty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['faculty', 'enrollment_batch'], name='student_fac_year_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='student_name_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='subject_name_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['faculty'], name='subject_faculty_idx'),
        ),
    ]
