# Generated by Django 6.0.3 on 2026-04-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('student', '0003_normalize_faculty_and_enrollment_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('submission_file', models.FileField(blank=True, default=None, null=True, upload_to='assignment_submissions/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='assignment.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_recipients', to='student.student')),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
