# Generated by Django 6.0.3 on 2026-04-06

from django.db import migrations, models


def populate_submission_status(apps, schema_editor):
    AssignmentRecipient = apps.get_model('assignment', 'AssignmentRecipient')
    for recipient in AssignmentRecipient.objects.all():
        recipient.submission_status = 'submitted' if recipient.is_submitted else 'pending'
        recipient.save(update_fields=['submission_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignment_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentrecipient',
            name='submission_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('resubmitted', 'Resubmitted')], default='pending', max_length=20),
        ),
        migrations.RunPython(populate_submission_status, migrations.RunPython.noop),
    ]