# Generated by Django 6.0.3 on 2026-04-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignmentrecipient_submission_status'),
        ('student', '0007_student_student_fac_year_idx_and_more'),
        ('teacher', '0004_teacher_teacher_name_idx_teacher_teacher_dept_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['faculty', 'enrollment_batch'], name='assignment_fac_year_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['teacher'], name='assignment_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='assignment_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_at'], name='assignment_created_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentrecipient',
            index=models.Index(fields=['student', 'submission_status'], name='assignment_rec_status_idx'),
        ),
    ]
