# Generated by Django 6.0.3 on 2026-04-05 15:25

from django.db import migrations, models


def merge_duplicate_attendance_rows(apps, schema_editor):
    Attendance = apps.get_model('attendance', 'Attendance')
    AttendanceEntry = apps.get_model('attendance', 'AttendanceEntry')

    duplicate_groups = (
        Attendance.objects.values('subject_id', 'faculty_id', 'enrollment_batch_id', 'attendance_date')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
    )

    for group in duplicate_groups:
        records = list(
            Attendance.objects.filter(
                subject_id=group['subject_id'],
                faculty_id=group['faculty_id'],
                enrollment_batch_id=group['enrollment_batch_id'],
                attendance_date=group['attendance_date'],
            ).order_by('created_at', 'id')
        )

        keeper = max(records, key=lambda record: record.entries.count())

        for record in records:
            if record.pk == keeper.pk:
                continue

            for entry in record.entries.all():
                keeper_entry, created = AttendanceEntry.objects.get_or_create(
                    attendance_id=keeper.pk,
                    student_id=entry.student_id,
                    defaults={
                        'status': entry.status,
                        'marked_at': entry.marked_at,
                    },
                )
                if not created and keeper_entry.status == 'unmarked' and entry.status != 'unmarked':
                    keeper_entry.status = entry.status
                    keeper_entry.marked_at = entry.marked_at
                    keeper_entry.save(update_fields=['status', 'marked_at'])
                entry.delete()

            record.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('student', '0004_subject'),
        ('teacher', '0002_teacher_faculties'),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_attendance_rows, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('enrollment_batch__isnull', False), ('faculty__isnull', False), ('subject__isnull', False)), fields=('subject', 'faculty', 'enrollment_batch', 'attendance_date'), name='unique_attendance_subject_faculty_year_date'),
        ),
    ]
