# Generated by Django 6.0.3 on 2026-04-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_weeklyclassschedule'),
        ('student', '0007_student_student_fac_year_idx_and_more'),
        ('teacher', '0004_teacher_teacher_name_idx_teacher_teacher_dept_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date'], name='attendance_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['faculty', 'enrollment_batch'], name='attendance_fac_year_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['teacher', 'attendance_date'], name='attendance_teacher_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['subject', 'attendance_date'], name='attendance_subject_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceentry',
            index=models.Index(fields=['student', 'status'], name='attendance_entry_status_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyclassschedule',
            index=models.Index(fields=['faculty', 'enrollment_batch', 'day_of_week'], name='weekly_fac_year_day_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyclassschedule',
            index=models.Index(fields=['teacher', 'day_of_week'], name='weekly_teacher_day_idx'),
        ),
    ]
